defaults:
  - /defaults.yaml
  - /comparison/_base_afhqv2.yaml

# pretrained EDM UNet (learned reference)
experiment:
  run_name: cmp_afhqv2_edm_unet
  tags: [comparison, afhqv2, edm_unet, heun]

model:
  name: edm_unet
  params:
    use_fp16: false
