defaults:
  - /defaults.yaml

experiment:
  run_name: nearest_dataset_ffhq
  tags: [baseline, nearest, ffhq]

dataset:
  name: ffhq
  split: train
  download: true
  batch_size: 256
  subset_size: null
  resolution: 64

model:
  name: nearest_dataset
  params: {}
